### ISSUE TITLE
App wrongly reports user has voted when vote may fail

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/token-frontend#1045]
TFE says “You voted For” even if the vote has not necessarily been made. I have experienced this in the wild with something like 30–50% of my voter attempts not registered on chain despite the text saying I voted.

Looks to me like it displays this text as soon as the txn is sent to a node and then updates to “You voted For on <date>” once it's actually recorded on chain. 

But the first part can fail to get your vote in for several reasons and this happens quite often, especially using the default wallet config for mainnet as this sometimes send to a data node like Lovali which fails to forward the tx. 

Obviously the node that causes this to fail a lot should be fixed (though it’s not clear to me if there’s also any front end error exacerbating this) but as it’s a decentralised and distributed system, the message in the first instance should be more like “Vote For proposal pending” and there should be some time after which it fails or some way to detect failure which currently doesn’t happen.

This has a real life production impact because we are trying to get a governance vote through and there could be users who run they have voted but have not, and we are currently short of the participation threshold.

**Comment by mattrussell36** [comment]
So we actually poll the vote data every 5 seconds so we should see the users vote pop up in the yes/no vote data set eventually (if successful). So I think we can easily do as you suggest and just indicate that the vote is pending, and keep it as pending until we see the vote. Perhaps we also use a timer so that if more than x amount of time (1 minute?) passes without seeing the vote we can show a failure message.

**Comment by cpuja84** [comment]
Now the vote doesn't come straight back as For or Against but instead it registers it as Casting vote

<img width="1430" alt="Screenshot 2021-12-09 at 15 12 41" src="https://user-images.githubusercontent.com/69709857/145425931-b783156b-3590-4a15-a47c-d328477bc285.png">

And send this message back when something is wrong in the network 
<img width="1427" alt="Screenshot 2021-12-09 at 15 12 54" src="https://user-images.githubusercontent.com/69709857/145425956-1414e2a3-1ad9-4bd6-a7be-a792298f7009.png">

But the issue is its happening now on every single vote for which another issue has been raised
